name: holo

services:
  database:
    image: "postgres:latest"
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin:/var/lib/pgadmin/

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    ports:
      - "${MINIO_ADMIN_PORT}:9090"
      - "${MINIO_PORT}:9000"
    env_file:
      - .env
    restart: unless-stopped
    command: server /data --console-address ":9090"

  api:
    image: ghcr.io/holoapp-dev/holo:main
    env_file:
      - .env
    ports:
      - 8080:8080

networks:
  postgres-network:
    driver: bridge

volumes:
  minio:
  pgadmin:
  postgres:
