services:
  database:
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${DOCKER_DIRECTORY}/db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ${DOCKER_DIRECTORY}/pgadmin-data/:/var/lib/pgadmin/

  minio:
    image: minio/minio
    volumes:
      -  ${DOCKER_DIRECTORY}/minio-data/:/data
    ports:
      - "${MINIO_ADMIN_PORT}:9090"
      - "${MINIO_PORT}:9000"
    env_file:
      - .env
    restart: unless-stopped
    command: server /data --console-address ":9090"

networks:
  postgres-network:
    driver: bridge